version: '3'
services:

  hiplot:
    build:
      context: ./hiplot
      dockerfile: Dockerfile
    volumes:
      - $DATA_FOLDER:/app/data      
    ports:
      - "5005:5005"

  manifold:
    build:
      context: ./manifold
      dockerfile: Dockerfile
    volumes:
      - $DATA_FOLDER:/app/data
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoiZ2F1dGFtYm9yZzEyMyIsImEiOiJjazc5MXZvem0wMDFlM2ZudjU5eWVlbDIyIn0.BchpTuaxZlIfAM16z2h4Qw"
    ports:
      - "127.0.0.1:8080:8080"

  tensorboard:
    build:
      context: ./tensorboard
      dockerfile: Dockerfile
    volumes:
      - $DATA_FOLDER:/app/data
    ports:
      - "6006:6006"

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    volumes:
      - $DATA_FOLDER:/app/data
      - $NOTEBOOKS_FOLDER:/app/notebooks
    ports:
      - "8888:8888"

  nbviewer:
    build:
      context: ./nbviewer
      dockerfile: Dockerfile
    volumes:      
      - $NOTEBOOKS_FOLDER:/notebooks
    ports:
      - "8890:8080"        

  zeppelin:
    build:
      context: ./zeppelin
      dockerfile: Dockerfile
    volumes:
      - $DATA_FOLDER:/zeppelin/data
      - $NOTEBOOKS_FOLDER:/zeppelin/notebook
    ports:
      - "8889:8080"      